/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void OnInfoClicked(GButton source, GEvent event) { //_CODE_:infoButton:464716:
  EnterInfoScreen();
} //_CODE_:infoButton:464716:

public void OnStartClicked(GButton source, GEvent event) { //_CODE_:startButton:936311:

  EnterEssayEditor();
  
} //_CODE_:startButton:936311:

public void OnBackClicked(GButton source, GEvent event) { //_CODE_:backButton:373704:
  Back();
} //_CODE_:backButton:373704:

public void OnManualDownloadButtonClicked(GButton source, GEvent event) { //_CODE_:manualDownloadButton:903249:
  DownloadUserManual();
} //_CODE_:manualDownloadButton:903249:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:controlsWindow:814485:
  appc.background(230);
} //_CODE_:controlsWindow:814485:

public void OnAskGemini(GButton source, GEvent event) { //_CODE_:askGeminiBbutton:328632:
  try
  {
    thread("AskGemini"); //by running on a seperate thread, the status label gets updated automagically instead of after the entire function has completed. g4p is weird.
  }
  catch (Exception e)
  {
    promptStatusLabel.setText("Servers overloaded. Try again later"); //only happens if gemini servers have too many requests and wont work (please dont happen while mr schattman is grading this)
  }
   
} //_CODE_:askGeminiBbutton:328632:

public void OnTypeInAskAwayField(GTextArea source, GEvent event) { //_CODE_:askAwayField:298145:
  println("askAwayField - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:askAwayField:298145:

public void OnTypedInEssayPathField(GTextField source, GEvent event) { //_CODE_:essayPathField:829266:
  println("essayPathField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:essayPathField:829266:

public void OnRefreshEssay(GButton source, GEvent event) { //_CODE_:refreshEssayButton:454847:
  RefreshEssayText();
} //_CODE_:refreshEssayButton:454847:

public void OnSpellcheckButtonClicked(GButton source, GEvent event) { //_CODE_:spellcheckButton:443578:
  SpellCheckEssay();
} //_CODE_:spellcheckButton:443578:

public void OnUnhighlightButtonClicked(GButton source, GEvent event) { //_CODE_:unhighlightButton:267502:
  unhighlightAll();
} //_CODE_:unhighlightButton:267502:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  infoButton = new GButton(this, 415, 530, 170, 70);
  infoButton.setText("INFO");
  infoButton.addEventHandler(this, "OnInfoClicked");
  startButton = new GButton(this, 415, 451, 170, 70);
  startButton.setText("START");
  startButton.addEventHandler(this, "OnStartClicked");
  backButton = new GButton(this, 21, 26, 80, 30);
  backButton.setText("Back");
  backButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  backButton.addEventHandler(this, "OnBackClicked");
  manualDownloadButton = new GButton(this, 668, 326, 80, 30);
  manualDownloadButton.setText("Download Manual");
  manualDownloadButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  manualDownloadButton.addEventHandler(this, "OnManualDownloadButtonClicked");
  downloadLabel = new GLabel(this, 754, 323, 206, 39);
  downloadLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  downloadLabel.setLocalColorScheme(GCScheme.RED_SCHEME);
  downloadLabel.setOpaque(false);
  controlsWindow = GWindow.getWindow(this, "Calliope Controls", 0, 0, 300, 600, JAVA2D);
  controlsWindow.noLoop();
  controlsWindow.setActionOnClose(G4P.KEEP_OPEN);
  controlsWindow.addDrawHandler(this, "win_draw1");
  askGeminiBbutton = new GButton(controlsWindow, 110, 270, 80, 30);
  askGeminiBbutton.setText("Ask away!");
  askGeminiBbutton.addEventHandler(this, "OnAskGemini");
  askAwayField = new GTextArea(controlsWindow, 90, 160, 120, 80, G4P.SCROLLBARS_VERTICAL_ONLY);
  askAwayField.setOpaque(true);
  askAwayField.addEventHandler(this, "OnTypeInAskAwayField");
  essayPathField = new GTextField(controlsWindow, 6, 503, 288, 51, G4P.SCROLLBARS_HORIZONTAL_ONLY);
  essayPathField.setPromptText("Paste the filepath to your essay here (text files only)");
  essayPathField.setOpaque(true);
  essayPathField.addEventHandler(this, "OnTypedInEssayPathField");
  refreshEssayButton = new GButton(controlsWindow, 102, 561, 80, 30);
  refreshEssayButton.setText("Refresh");
  refreshEssayButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  refreshEssayButton.addEventHandler(this, "OnRefreshEssay");
  spellcheckButton = new GButton(controlsWindow, 110, 80, 80, 30);
  spellcheckButton.setText("Spellcheck");
  spellcheckButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  spellcheckButton.addEventHandler(this, "OnSpellcheckButtonClicked");
  unhighlightButton = new GButton(controlsWindow, 110, 120, 80, 30);
  unhighlightButton.setText("Dismiss highlighting");
  unhighlightButton.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  unhighlightButton.addEventHandler(this, "OnUnhighlightButtonClicked");
  promptStatusLabel = new GLabel(controlsWindow, 10, 250, 280, 20);
  promptStatusLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  promptStatusLabel.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  promptStatusLabel.setOpaque(false);
  filepathStatusLabel = new GLabel(controlsWindow, 15, 484, 271, 20);
  filepathStatusLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  filepathStatusLabel.setOpaque(false);
  controlPanelTitle = new GLabel(controlsWindow, 95, 8, 110, 61);
  controlPanelTitle.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  controlPanelTitle.setText("Calliope Control Panel");
  controlPanelTitle.setOpaque(false);
  controlsWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton infoButton; 
GButton startButton; 
GButton backButton; 
GButton manualDownloadButton; 
GLabel downloadLabel; 
GWindow controlsWindow;
GButton askGeminiBbutton; 
GTextArea askAwayField; 
GTextField essayPathField; 
GButton refreshEssayButton; 
GButton spellcheckButton; 
GButton unhighlightButton; 
GLabel promptStatusLabel; 
GLabel filepathStatusLabel; 
GLabel controlPanelTitle; 
