/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void OnInfoClicked(GButton source, GEvent event) { //_CODE_:infoButton:464716:
  println("infoButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:infoButton:464716:

public void OnStartClicked(GButton source, GEvent event) { //_CODE_:startButton:936311:

  EnterEssayEditor();
  
} //_CODE_:startButton:936311:

public void OnBackClicked(GButton source, GEvent event) { //_CODE_:backButton:373704:
  Back();
} //_CODE_:backButton:373704:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:controlsWindow:814485:
  appc.background(230);
} //_CODE_:controlsWindow:814485:

public void OnTypeInGeminiQuestionField(GTextField source, GEvent event) { //_CODE_:geminiQuestionField:261763:
  println("geminiQuestionField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:geminiQuestionField:261763:

public void OnAskGemini(GButton source, GEvent event) { //_CODE_:askGeminiBbutton:328632:
  println("askGeminiBbutton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:askGeminiBbutton:328632:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  infoButton = new GButton(this, 415, 530, 170, 70);
  infoButton.setText("INFO");
  infoButton.addEventHandler(this, "OnInfoClicked");
  startButton = new GButton(this, 415, 451, 170, 70);
  startButton.setText("START");
  startButton.addEventHandler(this, "OnStartClicked");
  backButton = new GButton(this, 21, 26, 80, 30);
  backButton.setText("Back");
  backButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  backButton.addEventHandler(this, "OnBackClicked");
  controlsWindow = GWindow.getWindow(this, "Calliope Controls", 0, 0, 300, 600, JAVA2D);
  controlsWindow.noLoop();
  controlsWindow.setActionOnClose(G4P.KEEP_OPEN);
  controlsWindow.addDrawHandler(this, "win_draw1");
  geminiQuestionField = new GTextField(controlsWindow, 60, 177, 148, 66, G4P.SCROLLBARS_NONE);
  geminiQuestionField.setOpaque(true);
  geminiQuestionField.addEventHandler(this, "OnTypeInGeminiQuestionField");
  askGeminiBbutton = new GButton(controlsWindow, 96, 251, 80, 30);
  askGeminiBbutton.setText("Ask away!");
  askGeminiBbutton.addEventHandler(this, "OnAskGemini");
  controlsWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton infoButton; 
GButton startButton; 
GButton backButton; 
GWindow controlsWindow;
GTextField geminiQuestionField; 
GButton askGeminiBbutton; 
